name: "Playwright Downloader"
slug: "playwright_downloader"
version: "1.0.1"
description: "Addon для скачивания PDF счетов через Playwright"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
map:
  - share:rw
ports:
  8180/tcp: 8180
webui: "http://[HOST]:[PORT:8180]"
options:
  enabled: true
schema:
  url: str
  username: str?
  password: str?
  debug: bool
