name: "Playwright Downloader"
slug: "playwright_downloader"
version: "1.0.0"
description: "Addon для скачивания PDF счетов через Playwright"
arch:
  - amd64
  - arm64
  - aarch64
  - armhf
  - armv7
startup: services
boot: auto
options: {}
schema: {}
