name: "Playwright Downloader"
version: "1.0.0"
slug: "playwright_downloader"
description: "Addon для скачивания PDF счетов через Playwright"
arch:
  - amd64
  - arm64
startup: services
boot: auto
options: {}
schema: {}
ports:
  8000/tcp: 8000
map:
  - share:rw
